### ISSUE TITLE
ModuleNotFoundError: No module named 'modules_forge.forge_canvas'

### ISSUE THREAD

**Issue by FrakerKill** [lllyasviel/sd-forge-layerdiffuse#116]
[-] ADetailer initialized. version: 24.6.0, num models: 10
*** Error loading script: forge_layerdiffusion.py
    Traceback (most recent call last):
      File "C:\Users\ronsa\Downloads\stable-diffusion-webui-reForge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\ronsa\Downloads\stable-diffusion-webui-reForge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\ronsa\Downloads\stable-diffusion-webui-reForge\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py", line 21, in <module>
        from modules_forge.forge_canvas.canvas import ForgeCanvas
    ModuleNotFoundError: No module named 'modules_forge.forge_canvas'

---

**Comment by FrakerKill** [comment]
This is in a clean reforge installation

**Comment by LettleCreator** [comment]
upgrade your stable-diffusion-webui-forge

**Comment by FrakerKill** [comment]
> This is in a clean reforge installation

reforge, probably they must merge reforge with forge Gradio 4 updates
