### ISSUE TITLE
Error loading script: forge_layerdiffusion.py

### ISSUE THREAD

**Issue by Koxae** [lllyasviel/sd-forge-layerdiffuse#118]
Hello. The script stopped loading at startup.

```
*** Error loading script: forge_layerdiffusion.py
    Traceback (most recent call last):
      File "C:\ai\webui\modules\scripts.py", line 541, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\ai\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\ai\webui\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py", line 15, in <module>
        from lib_layerdiffusion.models import TransparentVAEDecoder, TransparentVAEEncoder
      File "C:\ai\webui\extensions\sd-forge-layerdiffuse\lib_layerdiffusion\models.py", line 10, in <module>
        from diffusers.models.unets.unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block
    ModuleNotFoundError: No module named 'diffusers.models.unets'
```

**Comment by KilluaMorales** [comment]
I got the same error.

**Comment by KilluaMorales** [comment]
I just figured out why it's showing that. You need to update forge. Here's a link to how:
https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/329#discussioncomment-8709692

**Comment by Koxae** [comment]
> I just figured out why it's showing that. You need to update forge. Here's a link to how: [lllyasviel/stable-diffusion-webui-forge#329 (reply in thread)](https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/329#discussioncomment-8709692)

Thank you. But unfortunately, Forge update is not possible now. The new version is not compatible with many extensions.

**Comment by navin-hariharan** [comment]
*** Error loading script: forge_layerdiffusion.py
    Traceback (most recent call last):
      File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py", line 11, in <module>
        from lib_layerdiffusion.utils import rgba2rgbfp32, to255unit8, crop_and_resize_image, forge_clip_encode
      File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\extensions\sd-forge-layerdiffuse\lib_layerdiffusion\utils.py", line 3, in <module>
        from backend import memory_management
    ImportError: cannot import name 'memory_management' from 'backend' (unknown location)

---

**Comment by rodion-b** [comment]
whats the solution - getting same error?
