### ISSUE TITLE
ImportError: cannot import name 'memory_management' from 'backend'

### ISSUE THREAD

**Issue by navin-hariharan** [lllyasviel/sd-forge-layerdiffuse#120]
*** Error loading script: forge_layerdiffusion.py
    Traceback (most recent call last):
      File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py", line 11, in <module>
        from lib_layerdiffusion.utils import rgba2rgbfp32, to255unit8, crop_and_resize_image, forge_clip_encode
      File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\extensions\sd-forge-layerdiffuse\lib_layerdiffusion\utils.py", line 3, in <module>
        from backend import memory_management
    ImportError: cannot import name 'memory_management' from 'backend' (unknown location)

---

**Comment by willgon123** [comment]
Have you solved this problem? I encountered this trouble too

**Comment by navin-hariharan** [comment]
Forge is going through an update! It should be fixed automatically!

**Comment by DiegoRRR** [comment]
No way to fix this without updating Forge?

**Comment by navin-hariharan** [comment]
It's been fixed for the latest version of forge!!

**Comment by toniodelsol** [comment]
Still the problem for me...
*** Error loading script: forge_layerdiffusion.py
    Traceback (most recent call last):
      File "C:\Users\antoi\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\antoi\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\antoi\stable-diffusion-webui\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py", line 11, in <module>
        from lib_layerdiffusion.utils import rgba2rgbfp32, to255unit8, crop_and_resize_image, forge_clip_encode
      File "C:\Users\antoi\stable-diffusion-webui\extensions\sd-forge-layerdiffuse\lib_layerdiffusion\utils.py", line 3, in <module>
        from backend import memory_management
    ModuleNotFoundError: No module named 'backend'

**Comment by secretlycarl** [comment]
@toniodelsol same issue here. I tried `pip install backend` in the venv but then the error changed to something like `unable to import memory_management from backend`
