### ISSUE TITLE
 AttributeError: 'Linear' object has no attribute 'in_features'

### ISSUE THREAD

**Issue by s4130** [lllyasviel/sd-forge-layerdiffuse#126]
我英语不好,所以直接用中文吧
版本: [f2.0.1v1.10.1-previous-399-g852e8856] •  python: 3.10.11  •  torch: 2.3.1+cu121  •  xformers: 0.0.27  •  gradio: 4.40.0  •  checkpoint: [15012c538f]
每次使用layerdiffuse都会显示以下错误:
```[LayerDiffuse] LayerMethod.FG_ONLY_ATTN_SD15
*** Error running process_before_every_sampling: D:\sd-webui-aki-v4.5\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.5\modules\scripts.py", line 892, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\sd-webui-aki-v4.5\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py", line 192, in process_before_every_sampling
        patcher = AttentionSharingPatcher(unet, frames=1, use_control=False)
      File "D:\sd-webui-aki-v4.5\extensions\sd-forge-layerdiffuse\lib_layerdiffusion\attention_sharing.py", line 207, in __init__
        u = AttentionSharingUnit(attn_module, frames=frames, use_control=use_control, rank=rank)
      File "D:\sd-webui-aki-v4.5\extensions\sd-forge-layerdiffuse\lib_layerdiffusion\attention_sharing.py", line 35, in __init__
        q_in_channels, q_out_channels = module.to_q.in_features, module.to_q.out_features
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\torch\nn\modules\module.py", line 1709, in __getattr__
        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
    AttributeError: 'Linear' object has no attribute 'in_features'

---
```
并且几乎没有效果
![image](https://github.com/user-attachments/assets/34fdeb3c-a55d-4529-9060-d7b768e885d7)

**Comment by G7b9** [comment]
我也是这个问题，好像是模型参数或者结构有问题
